# config/routes.yaml

app_homepage:
    path: /
    controller: App\Controller\MonController::maPremierePage

# config/routes.yaml

app_login:
    path: /login
    controller: App\Controller\SecurityController::login